import { initializeApp, getApps, getApp } from 'firebase/app';
import {
  getAuth,
  signInWithPopup,
  GoogleAuthProvider,
  onAuthStateChanged,
  User,
  signOut,
} from 'firebase/auth';
import {
  getFirestore,
  doc,
  setDoc,
  collection,
  getDocs,
  deleteDoc,
  Firestore,
} from 'firebase/firestore';
import firebaseConfig from '../../firebase-applet-config.json';
import { ScriptSegment } from '../types';

// Initialize Firebase App
const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();
export const auth = getAuth(app);
export const firestore: Firestore = getFirestore(app, firebaseConfig.firestoreDatabaseId);

// Google Auth Provider with Drive and Gmail scopes
const provider = new GoogleAuthProvider();
provider.addScope('https://www.googleapis.com/auth/drive');
provider.addScope('https://www.googleapis.com/auth/drive.file');
provider.addScope('https://www.googleapis.com/auth/drive.readonly');
provider.addScope('https://www.googleapis.com/auth/gmail.send');
provider.addScope('https://www.googleapis.com/auth/gmail.compose');
provider.addScope('https://www.googleapis.com/auth/gmail.readonly');

// In-memory token cache (never stored in localStorage)
let cachedAccessToken: string | null = null;
let isSigningIn = false;

export const initAuthListener = (
  onAuthSuccess: (user: User, token: string) => void,
  onAuthFailure: () => void
) => {
  return onAuthStateChanged(auth, async (user: User | null) => {
    if (user && cachedAccessToken) {
      onAuthSuccess(user, cachedAccessToken);
    } else {
      if (!isSigningIn) {
        onAuthFailure();
      }
    }
  });
};

export const signInWithGoogle = async (): Promise<{ user: User; accessToken: string } | null> => {
  try {
    isSigningIn = true;
    const result = await signInWithPopup(auth, provider);
    const credential = GoogleAuthProvider.credentialFromResult(result);
    if (!credential?.accessToken) {
      throw new Error('Failed to retrieve access token from Google Sign-In.');
    }
    cachedAccessToken = credential.accessToken;
    return { user: result.user, accessToken: cachedAccessToken };
  } finally {
    isSigningIn = false;
  }
};

export const logoutGoogle = async () => {
  await signOut(auth);
  cachedAccessToken = null;
};

export const getAccessToken = (): string | null => {
  return cachedAccessToken;
};

/* ===================================================================
 * GOOGLE DRIVE API INTEGRATION
 * =================================================================== */

export interface GoogleDriveFile {
  id: string;
  name: string;
  mimeType: string;
  size?: string;
  modifiedTime?: string;
}

export const listGoogleDriveFiles = async (): Promise<GoogleDriveFile[]> => {
  const token = getAccessToken();
  if (!token) throw new Error('Not authenticated with Google Workspace');

  const res = await fetch(
    'https://www.googleapis.com/drive/v3/files?pageSize=25&q=trashed=false&fields=files(id,name,mimeType,size,modifiedTime)&orderBy=modifiedTime desc',
    {
      headers: { Authorization: `Bearer ${token}` },
    }
  );

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to list Google Drive files');
  }

  const data = await res.json();
  return data.files || [];
};

export const readGoogleDriveFileContent = async (fileId: string): Promise<string> => {
  const token = getAccessToken();
  if (!token) throw new Error('Not authenticated with Google Workspace');

  const res = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}?alt=media`, {
    headers: { Authorization: `Bearer ${token}` },
  });

  if (!res.ok) {
    throw new Error('Failed to download Google Drive file content');
  }

  return await res.text();
};

export const uploadPodcastToDrive = async (
  title: string,
  audioBlobUrl: string,
  script: ScriptSegment[]
): Promise<{ fileId: string; webViewLink?: string }> => {
  const token = getAccessToken();
  if (!token) throw new Error('Not authenticated with Google Workspace');

  // Fetch the audio blob from the local blob URL
  const audioResponse = await fetch(audioBlobUrl);
  const audioBlob = await audioResponse.blob();

  const boundary = '-------PodcastAIDriveUpload' + Math.random().toString(36).substring(2);
  const delimiter = `\r\n--${boundary}\r\n`;
  const closeDelimiter = `\r\n--${boundary}--`;

  const metadata = {
    name: `${title || 'Podcast Episode'}.wav`,
    mimeType: 'audio/wav',
    description: `Generated by Podcast AI Studio with ${script.length} speaker turns.`,
  };

  const metadataPart =
    delimiter +
    'Content-Type: application/json; charset=UTF-8\r\n\r\n' +
    JSON.stringify(metadata) +
    '\r\n';

  const audioBytes = await audioBlob.arrayBuffer();

  // Construct multipart body
  const multipartPrefix = new TextEncoder().encode(
    metadataPart +
      delimiter +
      'Content-Type: audio/wav\r\n' +
      'Content-Transfer-Encoding: binary\r\n\r\n'
  );
  const multipartSuffix = new TextEncoder().encode(closeDelimiter);

  const fullPayload = new Uint8Array(
    multipartPrefix.byteLength + audioBytes.byteLength + multipartSuffix.byteLength
  );
  fullPayload.set(multipartPrefix, 0);
  fullPayload.set(new Uint8Array(audioBytes), multipartPrefix.byteLength);
  fullPayload.set(multipartSuffix, multipartPrefix.byteLength + audioBytes.byteLength);

  const uploadRes = await fetch(
    'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink',
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': `multipart/related; boundary=${boundary}`,
      },
      body: fullPayload,
    }
  );

  if (!uploadRes.ok) {
    const err = await uploadRes.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to upload podcast to Google Drive');
  }

  const uploadData = await uploadRes.json();
  return { fileId: uploadData.id, webViewLink: uploadData.webViewLink };
};

/* ===================================================================
 * GMAIL API INTEGRATION
 * =================================================================== */

export const sendPodcastViaGmail = async (
  recipientEmail: string,
  subject: string,
  podcastTitle: string,
  transcriptSnippet: string,
  durationSec: number
): Promise<{ success: boolean; id: string }> => {
  const token = getAccessToken();
  if (!token) throw new Error('Not authenticated with Google Workspace');

  const minutes = Math.floor(durationSec / 60);
  const seconds = Math.floor(durationSec % 60);
  const durationStr = `${minutes}:${seconds.toString().padStart(2, '0')}`;

  const emailLines = [
    `To: ${recipientEmail}`,
    `Subject: =?UTF-8?B?${btoa(unescape(encodeURIComponent(subject)))}?=`,
    'Content-Type: text/html; charset=UTF-8',
    '',
    `<!DOCTYPE html>
    <html dir="auto">
    <head><meta charset="utf-8"></head>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #1e293b; background-color: #f8fafc; padding: 20px;">
      <div style="max-width: 600px; margin: 0 auto; background: #ffffff; padding: 24px; border-radius: 12px; border: 1px solid #e2e8f0;">
        <h2 style="color: #d97706; margin-top: 0;">🎙️ ${podcastTitle}</h2>
        <p><strong>Duration:</strong> ${durationStr} min</p>
        <p><strong>Generated By:</strong> Podcast AI Local Studio (Multi-Speaker Engine)</p>
        <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
        <h4 style="margin-bottom: 8px;">Transcript Preview:</h4>
        <div style="background: #f1f5f9; padding: 14px; border-radius: 8px; font-size: 14px; color: #334155;">
          ${transcriptSnippet.replace(/\n/g, '<br/>')}
        </div>
        <p style="margin-top: 24px; font-size: 12px; color: #64748b;">
          Created offline with Podcast AI Local Studio.
        </p>
      </div>
    </body>
    </html>`,
  ];

  const rawEmail = emailLines.join('\r\n');
  const base64EncodedEmail = btoa(unescape(encodeURIComponent(rawEmail)))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');

  const sendRes = await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ raw: base64EncodedEmail }),
  });

  if (!sendRes.ok) {
    const err = await sendRes.json().catch(() => ({}));
    throw new Error(err.error?.message || 'Failed to send email via Gmail');
  }

  const result = await sendRes.json();
  return { success: true, id: result.id };
};

/* ===================================================================
 * FIRESTORE SYNC & PERSISTENCE
 * =================================================================== */

export const saveEpisodeToFirestore = async (
  userId: string,
  episodeId: string,
  title: string,
  durationSec: number,
  voices: string[],
  script: ScriptSegment[],
  driveFileId?: string
) => {
  const episodeRef = doc(firestore, `users/${userId}/episodes/${episodeId}`);
  await setDoc(episodeRef, {
    id: episodeId,
    userId,
    title,
    durationSec,
    voices,
    scriptJson: JSON.stringify(script),
    driveFileId: driveFileId || '',
    createdAt: new Date().toISOString(),
  });
};

export const fetchUserSavedEpisodes = async (userId: string) => {
  const episodesRef = collection(firestore, `users/${userId}/episodes`);
  const snapshot = await getDocs(episodesRef);
  return snapshot.docs.map(docSnap => docSnap.data());
};
